export interface ChartControlConfig {
  engName: string;
  ruName: string;
  color: string;
  isControlTooltip: boolean;
  controlTooltipText?: string;
  hasUnits?: boolean;
  units?: string;
  isOnChart: boolean;
  isAnnotation: boolean;
  isControl: boolean;
  defaultActive: boolean;
  tooltipText?: string;
}

export const chartCompareConfigObject: ChartControlConfig[] = [
  { 
    engName: 'cart', 
    ruName: 'Корзина, шт', 
    color: '#00B69B', 
    isControlTooltip: false, 
    hasUnits: false, 
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Сколько раз товар был добавлен в корзину после клика по рекламе. Показывает рост интереса и намерение купить',
  },
  { 
    engName: 'orders', 
    ruName: 'Заказы, шт', 
    color: '#F93C65', 
    isControlTooltip: false, 
    hasUnits: false, 
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Общее число оформленных заказов, атрибутированных к данной рекламной кампании',
  },
  { 
    engName: 'order_item_count', 
    ruName: 'Заказано, шт', 
    color: '#EC4899', 
    isControlTooltip: false, 
    hasUnits: false, 
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Суммарное количество единиц товара во всех заказах, привлеченных этой кампанией',
  },
  { 
    engName: 'expected_purchase', 
    ruName: 'Прогноз выкуп, шт', 
    color: '#90DAFF', 
    isControlTooltip: false, 
    hasUnits: false, 
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Ожидаемое количество единиц товара, которые будут оплачены. Для точного расчёта используется финальный процент выкупа на основе данных 14-дневной давности, когда все заказы уже перешли в статус «Выкуплен» или «Возврат/Невыкуп». Это исключает влияние незавершённых заказов на статистику',
  },
  { 
    engName: 'view_click', 
    ruName: 'Просмотры → Клик (CTR), %', 
    color: '#10B981', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '%',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Коэффициент кликабельности объявления. Показывает, какая доля показов привлекла внимание пользователя и вызвала переход. Ключевой показатель релевантности рекламного объявления',
  },
  { 
    engName: 'click_cart', 
    ruName: 'Клик → Корзина, %', 
    color: '#059669', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '%',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Доля пользователей, которые после перехода на карточку проявили серьезное намерение к покупке, добавив товар в корзину. Говорит о качестве карточки и оффера',
  },
  { 
    engName: 'cart_order', 
    ruName: 'Корзина → Заказ, %', 
    color: '#FFA1EB', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '%',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Показывает эффективность завершения покупки. Отражает, насколько легко пользователю оформить заказ после добавления в корзину',
  },
  { 
    engName: 'view_order', 
    ruName: 'Просмотр → Заказ, %', 
    color: '#065F46', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '%',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Ключевой показатель общей эффективности кампании: какая часть всех показов привела к оформлению заказа. Формула: (Заказы / Просмотры) * 100%',
  },
  { 
    engName: 'expected_order_purchase', 
    ruName: 'Прогноз Заказ → Выкуп, %', 
    color: '#88E473', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '%',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Ожидаемая доля заказанных товаров, которая будет оплачена. Для точности используется конверсия в выкуп по заказам, завершенным 14 дней назад, что исключает влияние "висящих" заказов',
  },
  { 
    engName: 'expected_click_purchase', 
    ruName: 'Прогноз Клик → Выкуп, %', 
    color: '#022C22', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '%',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Показывает, какой процент кликов по рекламе в итоге конвертируется в выкуп. Расчет основан на финальных данных о выкупе товаров за предыдущие периоды',
  },
  { 
    engName: 'views', 
    ruName: 'Просмотры, шт', 
    color: '#5329FF', 
    isControlTooltip: false, 
    hasUnits: false, 
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Сколько раз ваше рекламное объявление было показано пользователям площадки в выбранном периоде. Базовый показатель охвата аудитории',
  },
  { 
    engName: 'clicks', 
    ruName: 'Клики, шт', 
    color: '#F0AD00', 
    isControlTooltip: false, 
    hasUnits: false, 
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Число переходов пользователей на вашу карточку товара после показа рекламного объявления. Отражает уровень интереса',
  },
  { 
    engName: 'cpc', 
    ruName: 'CPC, %', 
    color: '#8B5CF6', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '₽',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Рассчитывается как Расходы на рекламу / Клики. Показатель того, сколько в среднем вы платите за один переход на карточку',
  },
  { 
    engName: 'avg_cpm', 
    ruName: 'Средний CPM за период, ₽', 
    color: '#A855F7', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '₽',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Средняя стоимость 1000 показов рекламного объявления в рамках данной рекламной кампании за выбранный период. Показатель помогает понять, сколько стоит охват аудитории на уровне показов, независимо от кликов или других действий. Формула: (Расходы на рекламу / Просмотры) * 1000',
  },
  // { 
  //   engName: 'avg_position', 
  //   ruName: 'Средняя позиция', 
  //   color: '#C084FC', 
  //   isControlTooltip: false, 
  //   hasUnits: false, 
  //   isOnChart: true, 
  //   isAnnotation: false, 
  //   isControl: true, 
  //   defaultActive: true 
  // },
  { 
    engName: 'drr_orders', 
    ruName: 'ДРР заказы, %', 
    color: '#D8B4FE', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '%',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Показывает, какой процент от суммы всех оформленных заказов составляют затраты на рекламу. Помогает оценить рентабельность привлечения заказов. Формула: (Расходы на рекламу / Сумма заказов) * 100%',
  },
  { 
    engName: 'drr_purchase', 
    ruName: 'Прогноз ДРР (по выкупу), %', 
    color: '#E9D5FF', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '%',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Ожидаемый процент рекламных затрат от суммы прогнозируемой выручки. Более точный показатель рентабельности инвестиций в рекламу (ROAS), так как основан на прогнозе реальных продаж. Формула: (Расходы на рекламу / Прогноз выкупа на сумму) * 100%',
  },
  { 
    engName: 'cp_cart', 
    ruName: 'CPCart, ₽', 
    color: '#F3E8FF', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '₽',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Средние затраты на то, чтобы пользователь добавил товар в корзину. Оценивает эффективность рекламы на этапе формирования спроса. Формула: Расходы на рекламу / Добавления в корзину',
  },
  { 
    engName: 'expected_cps', 
    ruName: 'Прогноз CPS, ₽', 
    color: '#ADADAD', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '₽',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Оценка средних рекламных затрат на одну фактическую продажу (выкуп). Учитывает прогнозируемое количество выкупов. Формула: Расходы на рекламу / Прогноз выкупа (шт)',
  },
  { 
    engName: 'orders_amount', 
    ruName: 'Заказов на сумму, ₽', 
    color: '#6366F1', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '₽',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Общий объем заказов, привлеченных кампанией, в денежном выражении. До вычета возможных отмен и невыкупов',
  },
  { 
    engName: 'expected_purchase_amount', 
    ruName: 'Прогноз выкуп на сумму, ₽', 
    color: '#FFDC89', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '₽',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Оценка реальной выручки от кампании после выкупа товаров. Прогноз строится на финальном проценте выкупа, рассчитанном по заказам двухнедельной давности с известным итогом. Это позволяет оценить рентабельность кампании без искажений из-за незавершённых заказов. Формула: Сумма заказов × Исторический % выкупа',
  },
  { 
    engName: 'ad_spend', 
    ruName: 'Расходы на рекламу, ₽', 
    color: '#C7D61E', 
    isControlTooltip: false, 
    hasUnits: true, 
    units: '₽',
    isOnChart: true, 
    isAnnotation: false, 
    isControl: true, 
    defaultActive: true,
    tooltipText: 'Общая сумма, списанная площадкой за показы вашего рекламного объявления в выбранном периоде',
  },
];

