

export const mainTableConfig = [
    {
        key: 'date',
        title: 'Дата',
        dataIndex: 'date',
        width: 200,
        minWidth: 150,
        fixed: true,
        sortable: true,
        hidden: false,
        canToggle: true,
    },
    {
        key: 'revenue',
        title: 'Выручка, руб',
        dataIndex: 'revenue',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'orders',
        title: 'Заказы, шт',
        dataIndex: 'orders',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'avg_check',
        title: 'Средний чек, руб',
        dataIndex: 'avg_check',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'stock_quantity',
        title: 'Остатки на конец дня, шт',
        dataIndex: 'stock_quantity',
        width: 300,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'goods_quantity',
        title: 'Кол-во артикулов, шт',
        dataIndex: 'goods_quantity',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'avg_price',
        title: 'Средняя цена без СПП, руб',
        dataIndex: 'avg_price',
        width: 300,
        minWidth: 250,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'goods_with_sales_quantity',
        title: 'Артикулов с продажами, шт',
        dataIndex: 'goods_with_sales_quantity',
        width: 350,
        minWidth: 280,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'brands_quantity',
        title: 'Кол-во брендов, шт',
        dataIndex: 'brands_quantity',
        width: 300,
        minWidth: 250,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'brands_with_sales_quantity',
        title: 'Кол-во брендов с продажами, шт',
        dataIndex: 'brands_with_sales_quantity',
        width: 400,
        minWidth: 320,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
];

export const goodsTableConfig = [
    {
        key: 'wb_id_name',
        title: 'Товар',
        dataIndex: 'wb_id_name',
        width: 400,
        minWidth: 300,
        fixed: true,
        sortable: false,
        hidden: false,
        canToggle: false,
    },
    {
        key: 'share_percent',
        title: 'Доля заказов среди выборки, %',
        dataIndex: 'share_percent',
        width: 300,
        minWidth: 250,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '%',
    },
    {
        key: 'wb_id',
        title: 'Артикул',
        dataIndex: 'wb_id',
        width: 150,
        minWidth: 120,
        sortable: true,
        hidden: false,
        canToggle: true,
    },
    {
        key: 'brand_name',
        title: 'Бренд',
        dataIndex: 'brand_name',
        width: 150,
        minWidth: 120,
        sortable: true,
        hidden: false,
        canToggle: true,
    },
    {
        key: 'avg_price',
        title: 'Средняя цена без СПП, руб',
        dataIndex: 'avg_price',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'avg_discount',
        title: 'Средняя скидка без СПП, %',
        dataIndex: 'avg_discount',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '%',
    },
    {
        key: 'avg_check',
        title: 'Средний чек, руб',
        dataIndex: 'avg_check',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue',
        title: 'Выручка, руб',
        dataIndex: 'revenue',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
];

export const salesTableConfig = [
    {
        key: 'subject_name',
        title: 'Категория',
        dataIndex: 'subject_name',
        width: 300,
        minWidth: 250,
        fixed: true,
        sortable: true,
        hidden: false,
        canToggle: false,
    },
    {
        key: 'goods_quantity',
        title: 'Кол-во артикулов',
        dataIndex: 'goods_quantity',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'goods_with_sales_quantity',
        title: 'Артикулов с продажами, шт',
        dataIndex: 'goods_with_sales_quantity',
        width: 300,
        minWidth: 250,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'brands_quantity',
        title: 'Кол-во брендов, шт',
        dataIndex: 'brands_quantity',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'avg_price',
        title: 'Средняя цена без СПП, руб',
        dataIndex: 'avg_price',
        width: 300,
        minWidth: 250,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'avg_discount',
        title: 'Средняя скидка без СПП, %',
        dataIndex: 'avg_discount',
        width: 300,
        minWidth: 250,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '%',
    },
    {
        key: 'avg_check',
        title: 'Средний чек, руб',
        dataIndex: 'avg_check',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue',
        title: 'Выручка, руб',
        dataIndex: 'revenue',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue_dynamics',
        title: 'Динамика выручки',
        dataIndex: 'revenue_dynamics',
        width: 300,
        minWidth: 250,
        sortable: false,
        hidden: false,
        canToggle: true,
        units: 'руб',
        className: 'chart-column',
    },
    {
        key: 'orders',
        title: 'Заказы, шт',
        dataIndex: 'orders',
        width: 170,
        minWidth: 130,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'quantity',
        title: 'Остатки на конец периода, шт',
        dataIndex: 'quantity',
        width: 320,
        minWidth: 280,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
];

export const ordersStructByColorsTableConfig = [
    {
        key: 'color',
        title: 'Цвет',
        dataIndex: 'color',
        width: 270,
        minWidth: 200,
        fixed: true,
        sortable: true,
        hidden: false,
        canToggle: false,
    },
    {
        key: 'share_percent',
        title: 'Доля заказов среди выборки, %',
        dataIndex: 'share_percent',
        width: 170,
        minWidth: 140,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '%',
    },
    {
        key: 'goods_quantity',
        title: 'Кол-во артикулов',
        dataIndex: 'goods_quantity',
        width: 170,
        minWidth: 140,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'brands_quantity',
        title: 'Кол-во брендов, шт',
        dataIndex: 'brands_quantity',
        width: 170,
        minWidth: 140,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'avg_price',
        title: 'Средняя цена без СПП, руб',
        dataIndex: 'avg_price',
        width: 170,
        minWidth: 140,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'avg_discount_no_spp',
        title: 'Средняя скидка без СПП, %',
        dataIndex: 'avg_discount_no_spp',
        width: 160,
        minWidth: 130,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '%',
    },
    {
        key: 'avg_bill',
        title: 'Средний чек, руб',
        dataIndex: 'avg_bill',
        width: 160,
        minWidth: 130,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue',
        title: 'Выручка, руб',
        dataIndex: 'revenue',
        width: 160,
        minWidth: 130,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue_dynamics',
        title: 'Динамика выручки',
        dataIndex: 'revenue_dynamics',
        width: 200,
        minWidth: 170,
        sortable: false,
        hidden: false,
        canToggle: true,
        units: 'руб',
        className: 'chart-column',
    },
    {
        key: 'orders',
        title: 'Заказы, шт',
        dataIndex: 'orders',
        width: 160,
        minWidth: 130,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'orders_dynamics',
        title: 'Динамика заказов',
        dataIndex: 'orders_dynamics',
        width: 200,
        minWidth: 170,
        sortable: false,
        hidden: false,
        canToggle: true,
        units: 'шт',
        className: 'chart-column',
    },
    {
        key: 'lost_revenue',
        title: 'Упущенная выручка, руб',
        dataIndex: 'lost_revenue',
        width: 170,
        minWidth: 140,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
];

export const ordersStructByWarehousesTableConfig = [
    {
        key: 'warehouse_name',
        title: 'Склад',
        dataIndex: 'warehouse_name',
        width: 300,
        minWidth: 250,
        fixed: true,
        sortable: true,
        hidden: false,
        canToggle: false,
    },
    {
        key: 'share_percent',
        title: 'Доля заказов среди выборки, %',
        dataIndex: 'share_percent',
        width: 350,
        minWidth: 300,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '%',
    },
    {
        key: 'avg_check',
        title: 'Средний чек, руб',
        dataIndex: 'avg_check',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue',
        title: 'Выручка, руб',
        dataIndex: 'revenue',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue_dynamics',
        title: 'Динамика выручки',
        dataIndex: 'revenue_dynamics',
        width: 300,
        minWidth: 250,
        sortable: false,
        hidden: false,
        canToggle: true,
        units: 'руб',
        className: 'chart-column',
    },
    {
        key: 'orders',
        title: 'Заказы, шт',
        dataIndex: 'orders',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'orders_dynamics',
        title: 'Динамика заказов',
        dataIndex: 'orders_dynamics',
        width: 300,
        minWidth: 250,
        sortable: false,
        hidden: false,
        canToggle: true,
        units: 'шт',
        className: 'chart-column',
    },
];

export const ordersStructBySizesTableConfig = [
    {
        key: 'size_name',
        title: 'Размер',
        dataIndex: 'size_name',
        width: 300,
        minWidth: 250,
        fixed: true,
        sortable: true,
        hidden: false,
        canToggle: false,
    },
    {
        key: 'share_percent',
        title: 'Доля заказов среди выборки, %',
        dataIndex: 'share_percent',
        width: 350,
        minWidth: 300,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '%',
    },
    {
        key: 'avg_check',
        title: 'Средний чек, руб',
        dataIndex: 'avg_check',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue',
        title: 'Выручка, руб',
        dataIndex: 'revenue',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue_dynamics',
        title: 'Динамика выручки',
        dataIndex: 'revenue_dynamics',
        width: 300,
        minWidth: 250,
        sortable: false,
        hidden: false,
        canToggle: true,
        units: 'руб',
        className: 'chart-column',
    },
    {
        key: 'orders',
        title: 'Заказы, шт',
        dataIndex: 'orders',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'orders_dynamics',
        title: 'Динамика заказов',
        dataIndex: 'orders_dynamics',
        width: 300,
        minWidth: 250,
        sortable: false,
        hidden: false,
        canToggle: true,
        units: 'шт',
        className: 'chart-column',
    },
];
