
export const mainTableConfig = [
    {
        key: 'date',
        title: 'Дата',
        dataIndex: 'date',
        width: 200,
        minWidth: 150,
        fixed: true,
        sortable: true,
        hidden: false,
        canToggle: false,
    },
    {
        key: 'revenue',
        title: 'Выручка, руб',
        dataIndex: 'revenue',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'orders',
        title: 'Заказы, шт',
        dataIndex: 'orders',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'quantity',
        title: 'Остатки на конец дня, шт',
        dataIndex: 'quantity',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'price',
        title: 'Средняя цена без СПП, руб',
        dataIndex: 'price',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'discount',
        title: 'Общая скидка без СПП, %',
        dataIndex: 'discount',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '%',
    },
    {
        key: 'feedbacks',
        title: 'Количество отзывов на конец дня, шт',
        dataIndex: 'feedbacks',
        width: 300,
        minWidth: 250,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'rating',
        title: 'Динамика рейтинга',
        dataIndex: 'rating',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: ' '
    },
    {
        key: 'dumping',
        title: 'Коэффициент демпинга, %',
        dataIndex: 'dumping',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: true,
        canToggle: true,
        units: '%',
    },
];

export const byColorTableConfig = [
    {
        key: 'color_name',
        title: 'Товар',
        dataIndex: 'color_name',
        width: 200,
        minWidth: 150,
        fixed: true,
        sortable: true,
        hidden: false,
        canToggle: false,
    },
    {
        key: 'revenue',
        title: 'Выручка, руб',
        dataIndex: 'revenue',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue_dynamics',
        title: 'Динамика выручки',
        dataIndex: 'revenue_dynamics',
        width: 200,
        minWidth: 150,
        sortable: false,
        hidden: false,
        canToggle: false,
        className: 'chart-column',
    },
    {
        key: 'price',
        title: 'Средняя цена без СПП, руб',
        dataIndex: 'price',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'discount',
        title: 'Общая скидка без СПП, %',
        dataIndex: 'discount',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '%',
    },
    {
        key: 'orders',
        title: 'Заказы, шт',
        dataIndex: 'orders',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'quantity',
        title: 'Остатки на конец периода, шт',
        dataIndex: 'quantity',
        width: 280,
        minWidth: 220,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'lost_revenue',
        title: 'Упущенная выручка, руб',
        dataIndex: 'lost_revenue',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'dumping',
        title: 'Коэффициент демпинга, %',
        dataIndex: 'dumping',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: true,
        canToggle: true,
        units: '%',
    },
];

export const byWarehouseTableConfig = [
    {
        key: 'name',
        title: 'Склад',
        dataIndex: 'name',
        width: 200,
        minWidth: 150,
        fixed: true,
        sortable: true,
        hidden: false,
        canToggle: false,
    },
    {
        key: 'revenue',
        title: 'Выручка, руб',
        dataIndex: 'revenue',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue_dynamics',
        title: 'Динамика выручки',
        dataIndex: 'revenue_dynamics',
        width: 200,
        minWidth: 150,
        sortable: false,
        hidden: false,
        canToggle: false,
        className: 'chart-column',
    },
    {
        key: 'orders',
        title: 'Заказы, шт',
        dataIndex: 'orders',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'quantity',
        title: 'Остатки на конец периода, шт',
        dataIndex: 'quantity',
        width: 280,
        minWidth: 220,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'dumping',
        title: 'Коэффициент демпинга, %',
        dataIndex: 'dumping',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: true,
        canToggle: true,
        units: '%',
    },
    {
        key: 'turnover',
        title: 'Оборачиваемость, дней',
        dataIndex: 'turnover',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'дн',
    },
];

export const bySizeTableConfig = [
    {
        key: 'name',
        title: 'Товар',
        dataIndex: 'name',
        width: 200,
        minWidth: 150,
        fixed: true,
        sortable: true,
        hidden: false,
        canToggle: false,
    },
    {
        key: 'revenue',
        title: 'Выручка, руб',
        dataIndex: 'revenue',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'revenue_dynamics',
        title: 'Динамика выручки',
        dataIndex: 'revenue_dynamics',
        width: 200,
        minWidth: 150,
        sortable: false,
        hidden: false,
        canToggle: false,
        className: 'chart-column',
    },
    {
        key: 'price',
        title: 'Средняя цена без СПП, руб',
        dataIndex: 'price',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'discount',
        title: 'Общая скидка без СПП, %',
        dataIndex: 'discount',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '%',
    },
    {
        key: 'orders',
        title: 'Заказы, шт',
        dataIndex: 'orders',
        width: 200,
        minWidth: 150,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'quantity',
        title: 'Остатки на конец периода, шт',
        dataIndex: 'quantity',
        width: 280,
        minWidth: 220,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: 'шт',
    },
    {
        key: 'lost_revenue',
        title: 'Упущенная выручка, руб',
        dataIndex: 'lost_revenue',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: false,
        canToggle: true,
        units: '₽',
    },
    {
        key: 'dumping',
        title: 'Коэффициент демпинга, %',
        dataIndex: 'dumping',
        width: 250,
        minWidth: 200,
        sortable: true,
        hidden: true,
        canToggle: true,
        units: '%',
    },
];