export const keywordsSelectionTableConfig = [
    {
        key: 'query',
        title: 'Название',
        dataIndex: 'query',
        hidden: false,
        width: 385,
        minWidth: 385,
        units: ' ',
    },
    {
        key: 'frequency',
        title: 'Частота',
        dataIndex: 'frequency',
        hidden: false,
        width: 160,
        minWidth: 160,
        sortable: true,
        units: ' ',
        tooltipText: 'Суммарная частотность запроса за 30 дней'
    },
    {
        key: 'total_goods',
        title: 'Товаров',
        dataIndex: 'total_goods',
        hidden: false,
        width: 160,
        minWidth: 160,
        units: ' ',
    },
    {
        key: 'complexity',
        title: 'Сложность',
        dataIndex: 'complexity',
        hidden: false,
        width: 160,
        minWidth: 160,
        units: ' ',
        tooltipText: 'Показатель конкурентности запроса, основанный на соотношении спроса (частотности) и количества товаров в выдаче. Чем ниже значение, тем проще продвигать товар по этому запросу. Рассчитывается через нормированный коэффициент спроса относительно максимального значения по рынку.'
    },
    // {
    //     key: 'shows',
    //     title: 'Просмотры/мес',
    //     dataIndex: 'shows',
    //     hidden: false,
    //     width: 160,
    //     minWidth: 160,
    // },
    {
        key: 'serp',
        title: '',
        dataIndex: 'serp',
        hidden: false,
        units: '₽',
        width: 160,
        minWidth: 160,
    },
]