export const positionTrackingTableConfig = [
    {
        key: 'name',
        title: 'Товар',
        dataIndex: 'name',
        hidden: false,
    },
    {
        key: 'queries',
        title: 'Ключей',
        dataIndex: 'queries',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
    {
        key: 'shows',
        title: 'Просмотров',
        dataIndex: 'views',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
    {
        key: 'place',
        title: 'Средняя позиция',
        dataIndex: 'place',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
    {
        key: 'actions',
        title: '',
        dataIndex: 'actions',
        hidden: false,
        width: 50,
        minWidth: 50,
    },
]