export const positionTrackingSkuTableConfig = [
    {
        key: 'name',
        title: 'Название',
        dataIndex: 'name',
        hidden: false,
        width: 250,
    },
    {
        key: 'frequency',
        title: 'Частота',
        dataIndex: 'frequency',
        hidden: false,
        width: 150,
    },
    {
        key: 'goodsCount',
        title: 'Товаров',
        dataIndex: 'goodsCount',
        hidden: false,
        width: 150,
    },
    {
        key: 'mon',
        title: 'Пн 11.10',
        dataIndex: 'mon',
        hidden: false,
        width: 100,
    },
    {
        key: 'tue',
        title: 'Вт 12.10',
        dataIndex: 'tue',
        hidden: false,
        width: 100,
    },
    {
        key: 'wed',
        title: 'Ср 13.10',
        dataIndex: 'wed',
        hidden: false,
        width: 100,
    },
    {
        key: 'thu',
        title: 'Чт 14.10',
        dataIndex: 'thu',
        hidden: false,
        width: 100,
    },
    {
        key: 'fri',
        title: 'Пт 15.10',
        dataIndex: 'fri',
        hidden: false,
        width: 100,
    },
    {
        key: 'sat',
        title: 'Сб 16.10',
        dataIndex: 'sat',
        hidden: false,
        width: 100,
    },
    {
        key: 'sun',
        title: 'Вс 17.10',
        dataIndex: 'sun',
        hidden: false,
        width: 100,
    },
    {
        key: 'mon2',
        title: 'Пн 18.10',
        dataIndex: 'mon2',
        hidden: false,
        width: 100,
    },
    {
        key: 'tue2',
        title: 'Вт 19.10',
        dataIndex: 'tue2',
        hidden: false,
        width: 100,
    },
    {
        key: 'wed2',
        title: 'Ср 20.10',
        dataIndex: 'wed2',
        hidden: false,
        width: 100,
    },
].map(_ => ({ ..._, minWidth: _.width, maxWidth: _.width * 2 }))