export const positionCheckTableConfig = [
    {
        key: 'query',
        title: 'Название',
        dataIndex: 'query',
        hidden: false,
        width: 385,
        minWidth: 385,
    },
    {
        key: 'frequency',
        title: 'Частота',
        dataIndex: 'frequency',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
    {
        key: 'total_goods',
        title: 'Товаров',
        dataIndex: 'total_goods',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
    {
        key: 'complexity',
        title: 'Сложность',
        dataIndex: 'complexity',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
    {
        key: 'views_per_month',
        title: 'Просмотры/мес',
        dataIndex: 'views_per_month',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
    {
        key: 'serp',
        title: '',
        dataIndex: 'serp',
        hidden: false,
        units: '₽',
        width: 160,
        minWidth: 160,
    },
]


export const innerTableConfig = [
    {
        key: 'product_name',
        title: 'Товар',
        dataIndex: 'product_name',
        hidden: false,
        width: 385,
        minWidth: 385,
    },
    {
        key: 'views_per_month',
        title: 'Просмотры/мес',
        dataIndex: 'views_per_month',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
    {
        key: 'reviews',
        title: 'Отзывы',
        dataIndex: 'reviews',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
    {
        key: 'rating',
        title: 'Рейтинг товара',
        dataIndex: 'rating',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
    {
        key: 'price',
        title: 'Цена',
        dataIndex: 'price',
        hidden: false,
        width: 160,
        minWidth: 160,
    },
   
    {
        key: 'position',
        title: '№ в выдаче',
        dataIndex: 'position',
        hidden: false,
        units: '₽',
        width: 160,
        minWidth: 160,
    },
]