export const positionCheckTableConfig = [
    {
        key: 'query',
        title: 'Название',
        dataIndex: 'query',
        hidden: false,
        width: 385,
        minWidth: 385,
    },
    {
        key: 'frequency',
        title: 'Частота',
        dataIndex: 'frequency',
        hidden: false,
        width: 160,
        minWidth: 160,
        sortable: true,
        units: ' ',
        tooltipText: 'Суммарная частотность запроса за 30 дней'
    },
    {
        key: 'total_goods',
        title: 'Товаров',
        dataIndex: 'total_goods',
        hidden: false,
        width: 160,
        minWidth: 160,
        units: ' ',
    },
    {
        key: 'complexity',
        title: 'Сложность',
        dataIndex: 'complexity',
        hidden: false,
        width: 160,
        minWidth: 160,
        units: ' ',
        tooltipText: 'Отражает уровень конкуренции по запросу относительно спроса. Чем меньше знаечние, тем привлекательнее ключ для раскрутки товара. Рассчитывается по уникальной формуле, учитывающей показатели частотности и количества товаров в выдаче по запросу'
    },
    {
        key: 'shows',
        title: 'Просмотры/мес',
        dataIndex: 'shows',
        hidden: false,
        width: 160,
        minWidth: 160,
        units: ' ',
        tooltipText: 'Показатель видимости товара в поиске по выбранному запросу. Рассчитывается на основе позиции в выдаче и не является счетчиком фактических просмотров.'
    },
    {
        key: 'serp',
        title: '',
        dataIndex: 'serp',
        hidden: false,
        units: '₽',
        width: 160,
        minWidth: 160,
    },
]


export const innerTableConfig = [
    {
        key: 'name',
        title: 'Товар',
        dataIndex: 'name',
        hidden: false,
        width: 375,
        minWidth: 375,
    },
    {
        key: 'shows',
        title: 'Просмотры/мес',
        dataIndex: 'shows',
        hidden: false,
        width: 160,
        minWidth: 160,
        units: ' ',
    },
    {
        key: 'feedbacks',
        title: 'Отзывы',
        dataIndex: 'feedbacks',
        hidden: false,
        width: 160,
        minWidth: 160,
        units: ' ',
    },
    {
        key: 'rating',
        title: 'Рейтинг товара',
        dataIndex: 'rating',
        hidden: false,
        width: 160,
        minWidth: 160,
        units: ' ',
    },
    {
        key: 'price',
        title: 'Цена',
        dataIndex: 'price',
        hidden: false,
        width: 160,
        minWidth: 160,
        units: ' ',
    },
   
    {
        key: 'number',
        title: '№ в выдаче',
        dataIndex: 'number',
        hidden: false,
        width: 160,
        minWidth: 160,
        units: ' ',
    },
]