export const serpPageTableConfig = [
    {
        key: 'pp',
        title: '№',
        dataIndex: 'pp',
        hidden: false,
        width: 35,
        minWidth: 35,
    },
    {
        key: 'name',
        title: 'Товар',
        dataIndex: 'name',
        hidden: false,
    },
    {
        key: 'number',
        title: '№ в выдаче',
        dataIndex: 'number',
        hidden: false,
        width: 120,
        minWidth: 120,
    },
    {
        key: 'ad',
        title: 'Тип',
        dataIndex: 'ad',
        hidden: false,
        width: 120,
        minWidth: 120,
    },
    {
        key: 'price',
        title: 'Цена',
        dataIndex: 'price',
        hidden: false,
        units: '₽',
        width: 90,
        minWidth: 90,
    },
    {
        key: 'feedbacks',
        title: 'Отзывы',
        dataIndex: 'feedbacks',
        hidden: false,
        units: ' ',
        width: 90,
        minWidth: 90,
    },
    {
        key: 'rating',
        title: 'Рейтинг',
        dataIndex: 'rating',
        hidden: false,
        width: 90,
        minWidth: 90,
    },
    {
        key: 'pics',
        title: 'Фото',
        dataIndex: 'pics',
        hidden: false,
        width: 90,
        minWidth: 90,
    },
]