export const ABC_ANALYSIS_TABLE_CONFIG_VER = '1';

export const getAbcAnalysisTableConfig = (viewType) => {
    const amountTitle = {
        profit: 'Прибыль',
        proceeds: 'Выручка',
    };
    const amountPercentTitle = {
        profit: 'Доля прибыли',
        proceeds: 'Доля выручки',
    };

    return [
        {
            title: 'Товар',
            dataIndex: 'item',
            key: 'item',
            width: 300,
            minWidth: 200,
            maxWidth: 400,
            sortable: false,
            hidden: false,
        },
        {
            title: 'Размер',
            dataIndex: 'tech_size',
            key: 'tech_size',
            width: 150,
            minWidth: 100,
            maxWidth: 200,
            sortable: false,
            hidden: false,
        },
        {
            title: 'Артикул поставщика',
            dataIndex: 'supplier_id',
            key: 'supplier_id',
            width: 200,
            minWidth: 150,
            maxWidth: 300,
            sortable: false,
            hidden: false,
        },
        {
            title: 'Артикул',
            dataIndex: 'wb_id',
            key: 'wb_id',
            width: 150,
            minWidth: 100,
            maxWidth: 200,
            sortable: false,
            hidden: false,
        },
        {
            title: amountTitle[viewType],
            dataIndex: 'amount',
            key: 'amount',
            width: 180,
            minWidth: 150,
            maxWidth: 250,
            sortable: true,
            hidden: false,
            units: '₽',
        },
        {
            title: amountPercentTitle[viewType],
            dataIndex: 'amount_percent',
            key: 'amount_percent',
            width: 200,
            minWidth: 150,
            maxWidth: 250,
            sortable: true,
            hidden: false,
            units: '%',
        },
        {
            title: 'Маржинальность',
            dataIndex: 'marginality',
            key: 'marginality',
            width: 180,
            minWidth: 150,
            maxWidth: 250,
            sortable: true,
            hidden: false,
            units: '%',
        },
        {
            title: 'ROI',
            dataIndex: 'roi',
            key: 'roi',
            width: 150,
            minWidth: 100,
            maxWidth: 200,
            sortable: true,
            hidden: false,
            units: '%',
        },
        {
            title: 'GMROI',
            dataIndex: 'gmroi',
            key: 'gmroi',
            width: 150,
            minWidth: 100,
            maxWidth: 200,
            sortable: true,
            hidden: viewType !== 'profit',
            units: '%',
        },
        {
            title: 'Логистика',
            dataIndex: 'logistic',
            key: 'logistic',
            width: 150,
            minWidth: 100,
            maxWidth: 200,
            sortable: true,
            hidden: false,
            units: '₽',
        },
        {
            title: 'Категория',
            dataIndex: 'category',
            key: 'category',
            width: 150,
            minWidth: 100,
            maxWidth: 200,
            sortable: true,
            hidden: false,
        },
    ];
};

