import {SortIcon, formatNumber} from '../../components/sharedComponents/ReportTable/ReportTable'
import { Tooltip, Flex } from 'antd';

function summaryRender(value, row) {
	if (row.key == 'summary'){
		return <Flex justify='space-between'>
			{value}: 
			<Tooltip title="Суммарные показатели за период">
				<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
					<rect x="0.75" y="0.75" width="18.5" height="18.5" rx="9.25" stroke="black" strokeOpacity="0.1" strokeWidth="1.5"/>
					<path d="M9.064 15V7.958H10.338V15H9.064ZM8.952 6.418V5.046H10.464V6.418H8.952Z" fill="#1A1A1A" fillOpacity="0.5"/>
				</svg>
			</Tooltip>
		</Flex>;
	}
	return value
}

function arrowRender(value) {
	let status = '';
	if (value > 0){
		status = 'table__arrow_positive'
	}
	if (value < 0){
		status = 'table__arrow_negative'
	}
	return (
		<span className={`table__arrow ${status}`}>
			{formatNumber(value)} %
			<svg width="16" height="12" viewBox="0 0 20 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M14 0L16.29 2.29L11.41 7.17L7.41 3.17L0 10.59L1.41 12L7.41 6L11.41 10L17.71 3.71L20 6V0H14Z" fill="currentColor"></path></svg>
		</span>
	)
}

function sorter(a, b, key) {
	if (a.key == 'summary' || b.key == 'summary'){
		return 0
	}
	return Number(a[key]) - Number(b[key])
}

export const COLUMNS = [
	{
		title: 'Неделя',
		dataIndex: 'week_label',
		fixed: 'left',
		width: 360,
		render: summaryRender
	},
	{
		title: 'Сред. цена продажи',
		// dataIndex: 'avg_price',
		dataIndex: 'avg_check',
		sorter: (a, b) => sorter(a, b, 'avg_check'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Реализация (сумма продаж по СПП)',
		// dataIndex: 'realization',
		dataIndex: 'avg_spp',
		sorter: (a, b) => sorter(a, b, 'avg_spp'), // Number(a.realization) - Number(b.realization),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		width: 240,
	},
	{
		title: 'Продажи',
		// dataIndex: 'sales',
		dataIndex: 'revenue',
		sorter: (a, b) => sorter(a, b, 'revenue'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value?.rub)} ₽
		<div className='table__arrow'>{formatNumber(value?.quantity)} шт</div></div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'К перечислению',
		dataIndex: 'transfer',
		sorter: (a, b) => sorter(a, b, 'transfer'), // Number(a.due) - Number(b.due),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Возвраты',
		dataIndex: 'returns',
		sorter: (a, b) => sorter(a, b, 'returns'), // Number(a.returns) - Number(b.returns),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Операционные расходы',
		dataIndex: 'op_expenses',
		sorter: (a, b) => sorter(a, b, 'op_expenses'), // Number(a.op_expenses) - Number(b.op_expenses),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Прочие удержания',
		dataIndex: 'other_retentions',
		sorter: (a, b) => sorter(a, b, 'other_retentions'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value?.rub)} ₽
			<div className='table__arrow'>{arrowRender(value?.percent)}</div>
		</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		// title: 'Себестоимость продаж',
		// dataIndex: 'cost',
		title: '?? Себестоимость',
		dataIndex: 'cost_price',
		sorter: (a, b) => sorter(a, b, 'cost_price'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		width: 240,
	},
	{
		// title: 'Себестоимость продаж',
		title: '?? Себестоимость',
		dataIndex: 'cost_price_percent',
		sorter: (a, b) => sorter(a, b, 'cost_price_percent'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		width: 240,
	},
	{
		title: 'Себестоимость на единицу',
		dataIndex: 'cost_price_per_one',
		sorter: (a, b) => sorter(a, b, 'cost_price_per_one'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		width: 240,
	},
	{
		title: 'Штрафы',
		dataIndex: 'penalties',
		sorter: (a, b) => sorter(a, b, 'penalties'), // Number(a.penalties) - Number(b.penalties),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: '! Доплаты',
		dataIndex: 'additional_payments',
		sorter: (a, b) => sorter(a, b, 'additional_payments'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: '! Все удержания WB',
		dataIndex: 'compensation_penalties',
		sorter: (a, b) => sorter(a, b, 'compensation_penalties'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value?.rub)} ₽<div className='table__arrow'>{formatNumber(value?.percent)}</div></div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Заказы, шт',
		dataIndex: 'order_count',
		// dataIndex: 'orders_count',
		sorter: (a, b) => sorter(a, b, 'order_count'), // Number(a.order_count) - Number(b.order_count),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} шт</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Заказы, руб',
		dataIndex: 'order_sum',
		// dataIndex: 'orders_amount',
		sorter: (a, b) => sorter(a, b, 'order_sum'), // Number(a.order_sum) - Number(b.order_sum),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Комиссия',
		// dataIndex: 'commission',
		dataIndex: 'wb_commission',
		sorter: (a, b) => sorter(a, b, 'wb_commission'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value?.rub)} ₽
			<div className='table__arrow'>{formatNumber(value?.percent)}</div>
		</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: '?? Компенсация',
		dataIndex: 'compensation',
		sorter: (a, b) => sorter(a, b, 'compensation'), // Number(a.compensation) - Number(b.compensation),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: '! Платная приёмка',
		dataIndex: 'acceptance',
		sorter: (a, b) => sorter(a, b, 'acceptance'), // Number(a.compensation) - Number(b.compensation),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽<div className='table__arrow'>{formatNumber(value?.quantity)} шт</div></div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: '! Компенсация брака',
		dataIndex: 'compensation_defects',
		sorter: (a, b) => sorter(a, b, 'compensation_defects'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value?.rub)} ₽<div className='table__arrow'>{formatNumber(value?.quantity)} шт</div></div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: '! Компенсации ущерба',
		dataIndex: 'compensation_damage',
		sorter: (a, b) => sorter(a, b, 'compensation_damage'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value?.rub)} ₽
		<div className='table__arrow'>{formatNumber(value?.quantity)} шт</div></div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: '?? Сред. стоимость логистики',
		dataIndex: 'avg_logistics',
		sorter: (a, b) => sorter(a, b, 'avg_logistics'), // Number(a.avg_logistics) - Number(b.avg_logistics),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Стоимость логистики',
		dataIndex: 'logistics',
		sorter: (a, b) => sorter(a, b, 'logistics'), // Number(a.logistics) - Number(b.logistics),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Хранение',
		dataIndex: 'storage',
		sorter: (a, b) => sorter(a, b, 'storage'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value?.rub)} ₽<div className='table__arrow'>{arrowRender(value?.percent)}</div></div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Кол-во отказов + возвраты',
		dataIndex: 'reject_returns',
		sorter: (a, b) => sorter(a, b, 'reject_returns'), // Number(a.reject_returns) - Number(b.reject_returns),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} шт</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Всего продаж',
		dataIndex: 'total_sales',
		// dataIndex: 'sales_count',
		sorter: (a, b) => sorter(a, b, 'total_sales'), // Number(a.total_sales) - Number(b.total_sales),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} шт</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Сред. процент выкупа',
		// dataIndex: 'avg_purchase_pct',
		dataIndex: 'purchase_percent',
		sorter: (a, b) => sorter(a, b, 'purchase_percent'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		// title: 'Сред. прибыль на 1 шт',
		title: 'Прибыль на 1 шт',
		// dataIndex: 'avg_profit_per_piece',
		dataIndex: 'profit_per_one',
		sorter: (a, b) => sorter(a, b, 'profit_per_one'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Налоги',
		// dataIndex: 'taxes',
		dataIndex: 'tax',
		sorter: (a, b) => sorter(a, b, 'tax'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: '! Налоговая база',
		dataIndex: 'tax_base',
		sorter: (a, b) => sorter(a, b, 'tax_base'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Прибыль',
		dataIndex: 'profit',
		sorter: (a, b) => sorter(a, b, 'profit'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: '?? Прибыль без опер. расходов',
		dataIndex: 'profit_no_op',
		sorter: (a, b) => sorter(a, b, 'profit_no_op'), // Number(a.profit_no_op) - Number(b.profit_no_op),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'ROI',
		// dataIndex: 'roi',
		dataIndex: 'return_on_investment',
		sorter: (a, b) => sorter(a, b, 'return_on_investment'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Маржинальность',
		// dataIndex: 'margin',
		dataIndex: 'marginality',
		sorter: (a, b) => sorter(a, b, 'marginality'),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Расходы на рекламу',
		dataIndex: 'ad_expenses',
		sorter: (a, b) => sorter(a, b, 'ad_expenses'), // Number(a.ad_expenses) - Number(b.ad_expenses),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'ДРР',
		dataIndex: 'drr',
		sorter: (a, b) => sorter(a, b, 'drr'), // Number(a.drr) - Number(b.drr),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Расходы на рекламу с бонусов',
		dataIndex: 'ad_bonus',
		sorter: (a, b) => sorter(a, b, 'ad_bonus'), // Number(a.ad_bonus) - Number(b.ad_bonus),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	// {
	// 	title: 'ДРР бонусов',
	// 	dataIndex: 'drr_bonus',
	// 	sorter: (a, b) => Number(a.drr_bonus) - Number(b.drr_bonus),
	// 	sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
	// 	filterOptions: true,
	// 	render: (value) => <div>{formatNumber(value)} %</div>,
	// 	// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
	// 	width: 240,
	// },
	{
		title: 'Общие расходы на рекламу',
		dataIndex: 'total_ad',
		sorter: (a, b) => sorter(a, b, 'total_ad'), // Number(a.total_ad) - Number(b.total_ad),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	// {
	// 	title: 'Общая ДРР',
	// 	dataIndex: 'total_drr',
	// 	sorter: (a, b) => Number(a.total_drr) - Number(b.total_drr),
	// 	sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
	// 	filterOptions: true,
	// 	render: (value) => <div>{formatNumber(value)} %</div>,
	// 	// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
	// 	width: 240,
	// },
	{
		title: 'Платная приемка',
		dataIndex: 'paid_accept',
		sorter: (a, b) => sorter(a, b, 'paid_accept'), // Number(a.paid_accept) - Number(b.paid_accept),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		width: 240,
	},
];
