import {SortIcon} from '../../components/sharedComponents/ReportTable/ReportTable'


function formatNumber(num) {
	if (!num){
		return '0';
	}
	return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1 ');
}

export const COLUMNS = [
	{
		title: 'Неделя',
		dataIndex: 'week_label',
		fixed: 'left',
		width: 240,
	},
	{
		title: 'Сред. цена продажи',
		dataIndex: 'avg_price',
		sorter: (a, b) => Number(a.avg_price) - Number(b.avg_price),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Реализация (сумма продаж по СПП)',
		dataIndex: 'realization',
		sorter: (a, b) => Number(a.realization) - Number(b.realization),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		width: 240,
	},
	{
		title: 'Продажи',
		dataIndex: 'sales',
		sorter: (a, b) => Number(a.sales) - Number(b.sales),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'К перечислению',
		dataIndex: 'transfer',
		sorter: (a, b) => Number(a.due) - Number(b.due),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Возвраты',
		dataIndex: 'returns',
		sorter: (a, b) => Number(a.returns) - Number(b.returns),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Операционные расходы',
		dataIndex: 'op_expenses',
		sorter: (a, b) => Number(a.op_expenses) - Number(b.op_expenses),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Прочие удержания',
		dataIndex: 'other_retentions',
		sorter: (a, b) => Number(a.other_retentions) - Number(b.other_retentions),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Себестоимость продаж',
		dataIndex: 'cost',
		sorter: (a, b) => Number(a.cost) - Number(b.cost),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		width: 240,
	},
	{
		title: 'Штрафы',
		dataIndex: 'penalties',
		sorter: (a, b) => Number(a.penalties) - Number(b.penalties),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Заказы, шт',
		dataIndex: 'order_count',
		sorter: (a, b) => Number(a.order_count) - Number(b.order_count),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} шт</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Заказы, руб',
		dataIndex: 'order_sum',
		sorter: (a, b) => Number(a.order_sum) - Number(b.order_sum),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Комиссия',
		dataIndex: 'commission',
		sorter: (a, b) => Number(a.commission) - Number(b.commission),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Компенсация',
		dataIndex: 'compensation',
		sorter: (a, b) => Number(a.compensation) - Number(b.compensation),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Сред. стоимость логистики',
		dataIndex: 'avg_logistics',
		sorter: (a, b) => Number(a.avg_logistics) - Number(b.avg_logistics),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Стоимость логистики',
		dataIndex: 'logistics',
		sorter: (a, b) => Number(a.logistics) - Number(b.logistics),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Хранение',
		dataIndex: 'storage',
		sorter: (a, b) => Number(a.storage) - Number(b.storage),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Кол-во отказов + возвраты',
		dataIndex: 'reject_returns',
		sorter: (a, b) => Number(a.reject_returns) - Number(b.reject_returns),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} шт</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Всего продаж',
		dataIndex: 'total_sales',
		sorter: (a, b) => Number(a.total_sales) - Number(b.total_sales),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} шт</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Сред. процент выкупа',
		dataIndex: 'buyout',
		sorter: (a, b) => Number(a.buyout) - Number(b.buyout),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Сред. прибыль на 1 шт',
		dataIndex: 'avg_profit_per_piece',
		sorter: (a, b) => Number(a.avg_profit_per_piece) - Number(b.avg_profit_per_piece),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Налоги',
		dataIndex: 'taxes',
		sorter: (a, b) => Number(a.taxes) - Number(b.taxes),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Прибыль',
		dataIndex: 'profit',
		sorter: (a, b) => Number(a.profit) - Number(b.profit),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Прибыль без опер. расходов',
		dataIndex: 'profit_no_op',
		sorter: (a, b) => Number(a.profit_no_op) - Number(b.profit_no_op),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'ROI',
		dataIndex: 'roi',
		sorter: (a, b) => Number(a.roi) - Number(b.roi),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
	},
	{
		title: 'Маржинальность',
		dataIndex: 'margin',
		sorter: (a, b) => Number(a.margin) - Number(b.margin),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Расходы на рекламу',
		dataIndex: 'ad_expenses',
		sorter: (a, b) => Number(a.ad_expenses) - Number(b.ad_expenses),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'ДРР',
		dataIndex: 'drr',
		sorter: (a, b) => Number(a.drr) - Number(b.drr),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Расходы на рекламу с бонусов',
		dataIndex: 'ad_bonus',
		sorter: (a, b) => Number(a.ad_bonus) - Number(b.ad_bonus),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'ДРР бонусов',
		dataIndex: 'drr_bonus',
		sorter: (a, b) => Number(a.drr_bonus) - Number(b.drr_bonus),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Общие расходы на рекламу',
		dataIndex: 'total_ad',
		sorter: (a, b) => Number(a.total_ad) - Number(b.total_ad),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Средний процент выкупа',
		dataIndex: 'avg_purchase_pct',
		sorter: (a, b) => Number(a.avg_purchase_pct) - Number(b.avg_purchase_pct),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Общая ДРР',
		dataIndex: 'total_drr',
		sorter: (a, b) => Number(a.total_drr) - Number(b.total_drr),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} %</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Платная приемка',
		dataIndex: 'priemka',
		sorter: (a, b) => Number(a.priemka) - Number(b.priemka),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		// filterIcon: ({filtered}) => <FilterIcon filtered={filtered}/>,
		width: 240,
	},
	{
		title: 'Платная приемка',
		dataIndex: 'paid_accept',
		sorter: (a, b) => Number(a.paid_accept) - Number(b.paid_accept),
		sortIcon: ({ sortOrder }) => <SortIcon sortOrder={sortOrder} />,
		filterOptions: true,
		render: (value) => <div>{formatNumber(value)} ₽</div>,
		width: 240,
	},
];
